export { default as Home } from './home/index';
export { default as Education } from './education/index';
export { default as Experience } from './experience/index';
export { default as Contact } from './contact';
export { default as Login } from './login/index';
export { default as Profile } from './profile';
export { default as ProfileId } from './profileId';
export { default as InfoCorona } from './infoCorona';
export { default as DetailDate } from './detailDate';
